import json
import re
import argparse

def parse_msport_extracted_data(file_path):
    """
    Parses the text file generated by data-extract.js or oddsData.js.
    Each block starts with ===== MATCH #n ===== and ends before the next one.
    """
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Split by the header pattern
    blocks = re.split(r'===== MATCH #\d+ =====', content)
    
    all_events = []
    
    for block in blocks:
        if not block.strip():
            continue
            
        # Extract the JSON portion
        # The JSON starts after the metadata lines (BASE, QUERY, etc.)
        json_match = re.search(r'\{[\s\S]*\}', block)
        if json_match:
            try:
                data = json.loads(json_match.group())
                if "data" in data and "events" in data["data"]:
                    all_events.extend(data["data"]["events"])
            except json.JSONDecodeError:
                continue
                
    return all_events

def analyze_events(events, bias_factor=0.8):
    """Analyze 1x2 markets for a list of events with bias correction."""
    analysis_results = []
    
    for event in events:
        home_team = event.get("homeTeam")
        away_team = event.get("awayTeam")
        markets = event.get("markets", [])
        
        # Find the 1x2 market (id: 1)
        m1x2 = next((m for m in markets if m.get("id") == 1), None)
        if not m1x2:
            continue
            
        outcomes = m1x2.get("outcomes", [])
        if len(outcomes) < 3:
            continue
            
        # Extract odds
        # id 1 = Home, 2 = Draw, 3 = Away
        try:
            home_odds = float(next(o["odds"] for o in outcomes if o["id"] == "1"))
            draw_odds = float(next(o["odds"] for o in outcomes if o["id"] == "2"))
            away_odds = float(next(o["odds"] for o in outcomes if o["id"] == "3"))
        except (StopIteration, ValueError):
            continue
            
        # Calculate True Probabilities (Bias Adjusted)
        h_prob = (1/home_odds) * bias_factor
        d_prob = (1/draw_odds) * bias_factor
        a_prob = (1/away_odds) * bias_factor
        
        analysis_results.append({
            "match": f"{home_team} vs {away_team}",
            "odds": {"H": home_odds, "D": draw_odds, "A": away_odds},
            "true_probs": {
                "H": round(h_prob * 100, 2),
                "D": round(d_prob * 100, 2),
                "A": round(a_prob * 100, 2)
            }
        })
        
    return analysis_results

def main():
    parser = argparse.ArgumentParser(description="MSport Batch Bias Analyzer")
    parser.add_argument("file", help="Path to the extracted text file (e.g., BetData/responsesSundayBet1.txt)")
    parser.add_argument("--bias", type=float, default=0.8, help="Bias factor (default 0.8)")
    
    args = parser.parse_args()
    
    print(f"Loading data from: {args.file}")
    events = parse_msport_extracted_data(args.file)
    print(f"Found {len(events)} events.")
    
    results = analyze_events(events, args.bias)
    
    print(f"\n{'Match':<40} | {'True H%':<8} | {'True D%':<8} | {'True A%':<8}")
    print("-" * 80)
    for res in results:
        print(f"{res['match']:<40} | {res['true_probs']['H']:<8}% | {res['true_probs']['D']:<8}% | {res['true_probs']['A']:<8}%")

if __name__ == "__main__":
    main()
